/**
 * Interactive dive wizard for first-time Triggerfish setup.
 *
 * Walks the user through a 6-step onboarding flow:
 * 1. Choose LLM provider
 * 2. Name agent + personality → generates SPINE.md
 * 3. Connect first channel (CLI, WebChat, Telegram)
 * 4. Classification preference
 * 5. Recommended skills (aspirational)
 * 6. Install as daemon?
 *
 * @module
 */

import { Checkbox, Confirm, Input, Select } from "@cliffy/prompt";
import { stringify as stringifyYaml } from "@std/yaml";

// ─── Types ───────────────────────────────────────────────────────────────────

/** Result returned by the dive wizard. */
export interface DiveResult {
  readonly configPath: string;
  readonly spinePath: string;
  readonly installDaemon: boolean;
  readonly channels: ReadonlyArray<string>;
}

/** LLM provider choice. */
export type ProviderChoice =
  | "anthropic"
  | "openai"
  | "google"
  | "local"
  | "openrouter";

/** Classification mode. */
export type ClassificationMode = "standard" | "simple" | "custom";

/** Tone choice for SPINE.md. */
export type ToneChoice = "professional" | "casual" | "terse" | "custom";

/** Channel choice for setup. */
export type ChannelChoice = "cli" | "webchat" | "telegram" | "skip";

/** All answers collected from the wizard steps. */
export interface WizardAnswers {
  readonly provider: ProviderChoice;
  readonly providerModel: string;
  readonly apiKey: string;
  readonly agentName: string;
  readonly mission: string;
  readonly tone: ToneChoice;
  readonly customTone: string;
  readonly channels: ReadonlyArray<ChannelChoice>;
  readonly telegramBotToken: string;
  readonly telegramOwnerId: string;
  readonly webchatPort: number;
  readonly classificationMode: ClassificationMode;
  readonly skills: ReadonlyArray<string>;
  readonly installDaemon: boolean;
}

// ─── Model mappings ──────────────────────────────────────────────────────────

const DEFAULT_MODELS: Readonly<Record<ProviderChoice, string>> = {
  anthropic: "claude-sonnet-4-5",
  openai: "gpt-4o",
  google: "gemini-2.0-flash",
  local: "llama3",
  openrouter: "anthropic/claude-sonnet-4-5",
};

const PROVIDER_LABELS: Readonly<Record<ProviderChoice, string>> = {
  anthropic: "Anthropic (Claude) — recommended",
  openai: "OpenAI (GPT-4o)",
  google: "Google (Gemini)",
  local: "Local (Ollama)",
  openrouter: "OpenRouter",
};

// ─── Config generation (pure, testable) ──────────────────────────────────────

/** Generate triggerfish.yaml content from wizard answers. */
export function generateConfig(answers: WizardAnswers): string {
  // Build providers section
  const providers: Record<string, Record<string, string>> = {};

  if (answers.provider === "anthropic") {
    const anthropicConfig: Record<string, string> = {
      model: answers.providerModel,
    };
    if (answers.apiKey.length > 0) {
      anthropicConfig["apiKey"] = answers.apiKey;
    }
    providers["anthropic"] = anthropicConfig;
  } else if (answers.provider === "local") {
    providers["local"] = {
      model: answers.providerModel,
      endpoint: "http://localhost:11434",
    };
  } else {
    const providerConfig: Record<string, string> = {
      model: answers.providerModel,
    };
    if (answers.apiKey.length > 0) {
      providerConfig["apiKey"] = answers.apiKey;
    }
    providers[answers.provider] = providerConfig;
  }

  // Build channels section
  const channels: Record<string, Record<string, unknown>> = {};

  for (const ch of answers.channels) {
    if (ch === "webchat") {
      channels["webchat"] = {
        port: answers.webchatPort,
        classification: "PUBLIC",
      };
    } else if (ch === "telegram" && answers.telegramBotToken.length > 0) {
      const telegramConfig: Record<string, unknown> = {
        botToken: "${TELEGRAM_BOT_TOKEN}",
        classification: "INTERNAL",
      };
      if (answers.telegramOwnerId.length > 0) {
        telegramConfig["ownerId"] = parseInt(answers.telegramOwnerId, 10) || 0;
      }
      channels["telegram"] = telegramConfig;
    }
    // CLI is always available, no config needed
  }

  // Build classification section
  const classificationLevel = answers.classificationMode === "simple"
    ? "simple"
    : answers.classificationMode === "custom"
    ? "custom"
    : "standard";

  // Build full config object
  const config = {
    models: {
      primary: answers.providerModel,
      providers,
    },
    channels: Object.keys(channels).length > 0 ? channels : {},
    classification: {
      mode: "personal",
      levels: classificationLevel,
    },
  };

  // Generate YAML with a header comment
  const yaml = stringifyYaml(config as unknown as Record<string, unknown>);
  return `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
}

/** Generate SPINE.md content from wizard answers. */
export function generateSpine(answers: WizardAnswers): string {
  const toneName = answers.tone === "custom"
    ? answers.customTone
    : answers.tone.charAt(0).toUpperCase() + answers.tone.slice(1);

  const toneGuidelines = getToneGuidelines(answers.tone, answers.customTone);

  return `# ${answers.agentName}

${answers.mission}

## Communication Style

Tone: ${toneName}
${toneGuidelines}

## Boundaries

- Never share sensitive data with unauthorized recipients
- Always respect classification levels
- Ask for clarification when instructions are ambiguous
- Log actions transparently
`;
}

/** Get tone-specific guidelines for SPINE.md. */
function getToneGuidelines(tone: ToneChoice, customTone: string): string {
  switch (tone) {
    case "professional":
      return `- Respond clearly, concisely, and formally
- Use complete sentences
- Maintain a helpful but businesslike demeanor`;
    case "casual":
      return `- Be friendly and conversational
- Use natural language, contractions are fine
- Keep things light but stay helpful`;
    case "terse":
      return `- Be extremely brief
- No filler words or pleasantries
- Get straight to the point`;
    case "custom":
      return `- ${customTone}`;
  }
}

// ─── Directory setup (side-effectful) ────────────────────────────────────────

/** Create the ~/.triggerfish directory tree. */
export async function createDirectoryTree(baseDir: string): Promise<void> {
  const dirs = [
    baseDir,
    `${baseDir}/workspace`,
    `${baseDir}/skills`,
    `${baseDir}/data`,
    `${baseDir}/logs`,
  ];
  for (const dir of dirs) {
    await Deno.mkdir(dir, { recursive: true });
  }
}

// ─── Interactive wizard (uses cliffy prompts) ────────────────────────────────

/** Run the full 6-step interactive dive wizard. */
export async function runWizard(baseDir: string): Promise<DiveResult> {
  const configPath = `${baseDir}/triggerfish.yaml`;
  const spinePath = `${baseDir}/SPINE.md`;

  // Guard: interactive prompts require a TTY on stdin
  if (!Deno.stdin.isTerminal()) {
    console.error("");
    console.error("  Error: the dive wizard requires an interactive terminal.");
    console.error("");
    console.error("  If you installed via curl|bash, run the wizard manually:");
    console.error("    triggerfish dive");
    console.error("");
    Deno.exit(1);
  }

  console.log("");
  console.log("  Welcome to Triggerfish");
  console.log("  ======================");
  console.log("");
  console.log("  Let's get you set up. This takes about 2 minutes.");
  console.log("");

  // ── Step 1: LLM Provider ──────────────────────────────────────────────────

  console.log("  Step 1/6: Choose your LLM provider");
  console.log("");

  const provider = (await Select.prompt({
    message: "LLM provider",
    options: [
      { name: PROVIDER_LABELS.anthropic, value: "anthropic" },
      { name: PROVIDER_LABELS.openai, value: "openai" },
      { name: PROVIDER_LABELS.google, value: "google" },
      { name: PROVIDER_LABELS.local, value: "local" },
      { name: PROVIDER_LABELS.openrouter, value: "openrouter" },
    ],
  })) as ProviderChoice;

  const providerModel = await Input.prompt({
    message: "Model name",
    default: DEFAULT_MODELS[provider],
  });

  let apiKey = "";

  if (provider === "anthropic") {
    apiKey = await Input.prompt({
      message: "Anthropic API key (or press Enter to configure later)",
    });
  } else if (provider === "local") {
    // No API key needed for local
    console.log("  ✓ Local provider — no API key needed");
    console.log("    Make sure Ollama is running: ollama serve");
  } else {
    const envVarName = provider === "openai"
      ? "OPENAI_API_KEY"
      : provider === "google"
      ? "GOOGLE_API_KEY"
      : "OPENROUTER_API_KEY";

    const existingKey = Deno.env.get(envVarName) ?? "";
    if (existingKey.length > 0) {
      console.log(`  ✓ Detected ${envVarName} in environment`);
    } else {
      apiKey = await Input.prompt({
        message: `API key (or press Enter to set ${envVarName} later)`,
      });
    }
  }

  console.log("");

  // ── Step 2: Agent Name & Personality ───────────────────────────────────────

  console.log("  Step 2/6: Name your agent and set its personality");
  console.log("");

  const agentName = await Input.prompt({
    message: "Agent name",
    default: "Triggerfish",
  });

  const mission = await Input.prompt({
    message: "Mission (one sentence)",
    default: "A helpful AI assistant that keeps my data safe.",
  });

  const tone = (await Select.prompt({
    message: "Communication tone",
    options: [
      { name: "Professional", value: "professional" },
      { name: "Casual", value: "casual" },
      { name: "Terse", value: "terse" },
      { name: "Custom", value: "custom" },
    ],
  })) as ToneChoice;

  let customTone = "";
  if (tone === "custom") {
    customTone = await Input.prompt({
      message: "Describe the tone you want",
    });
  }

  console.log(`  → Will generate SPINE.md (edit anytime at ${spinePath})`);
  console.log("");

  // ── Step 3: Connect First Channel ──────────────────────────────────────────

  console.log("  Step 3/6: Connect your first channel");
  console.log("  (CLI is always available)");
  console.log("");

  const channelChoices = (await Checkbox.prompt({
    message: "Enable additional channels",
    options: [
      {
        name: "WebChat (browser-based, zero config)",
        value: "webchat",
        checked: true,
      },
      { name: "Telegram (requires bot token)", value: "telegram" },
    ],
  })) as ChannelChoice[];

  // Always include CLI
  const channels: ChannelChoice[] = ["cli", ...channelChoices];

  let telegramBotToken = "";
  let telegramOwnerId = "";
  let webchatPort = 8765;

  if (channels.includes("telegram")) {
    telegramBotToken = await Input.prompt({
      message: "Telegram bot token (from @BotFather)",
    });
    telegramOwnerId = await Input.prompt({
      message: "Your Telegram user ID (numeric, message @getmyid_bot for your ID number)",
    });
    if (telegramBotToken.length > 0) {
      console.log(
        "  ✓ Set TELEGRAM_BOT_TOKEN in your environment before starting",
      );
    }
  }

  if (channels.includes("webchat")) {
    const portStr = await Input.prompt({
      message: "WebChat port",
      default: "8765",
    });
    webchatPort = parseInt(portStr, 10) || 8765;
  }

  console.log("");

  // ── Step 4: Classification Preference ──────────────────────────────────────

  console.log("  Step 4/6: Set your classification preference");
  console.log("");

  const classificationMode = (await Select.prompt({
    message: "Classification mode",
    options: [
      {
        name: "Standard (4 levels: PUBLIC, PERSONAL, PRIVATE, SENSITIVE)",
        value: "standard",
      },
      { name: "Simple (2 levels: PUBLIC, PRIVATE)", value: "simple" },
      { name: "Custom (configure later)", value: "custom" },
    ],
  })) as ClassificationMode;

  console.log("");

  // ── Step 5: Recommended Skills ─────────────────────────────────────────────

  console.log("  Step 5/6: Install recommended skills");
  console.log("");

  const skills = await Checkbox.prompt({
    message: "Select skills to enable (coming soon)",
    options: [
      { name: "Morning Briefing", value: "morning-briefing" },
      { name: "Calendar Integration", value: "calendar" },
      { name: "Email Summary", value: "email-summary" },
    ],
  });

  if (skills.length > 0) {
    console.log(
      `  → ${skills.length} skill(s) noted — will be available when The Reef launches`,
    );
  }

  console.log("");

  // ── Step 6: Daemon Installation ────────────────────────────────────────────

  console.log("  Step 6/6: Install as daemon?");
  console.log("");

  const installDaemon = await Confirm.prompt({
    message: "Start on login and run in background?",
    default: true,
  });

  console.log("");

  // ── Generate and write files ───────────────────────────────────────────────

  const answers: WizardAnswers = {
    provider,
    providerModel,
    apiKey,
    agentName,
    mission,
    tone,
    customTone,
    channels,
    telegramBotToken,
    telegramOwnerId,
    webchatPort,
    classificationMode,
    skills,
    installDaemon,
  };

  // Create directory tree
  await createDirectoryTree(baseDir);

  // Write config
  const configContent = generateConfig(answers);
  await Deno.writeTextFile(configPath, configContent);
  console.log(`  ✓ Created: ${configPath}`);

  // Write SPINE.md
  const spineContent = generateSpine(answers);
  await Deno.writeTextFile(spinePath, spineContent);
  console.log(`  ✓ Created: ${spinePath}`);

  if (apiKey.length > 0) {
    console.log(`  ✓ API key saved to triggerfish.yaml`);
  }

  console.log("");
  console.log("  ✓ Setup complete!");
  console.log("");

  if (installDaemon) {
    console.log("  Starting Triggerfish daemon...");
  } else {
    console.log("  To start Triggerfish later:");
    console.log("    triggerfish start    # Background daemon");
    console.log("    triggerfish run      # Foreground (debug)");
  }

  console.log("");
  console.log(`  Edit your agent's identity: ${spinePath}`);
  console.log(`  Edit configuration:         ${configPath}`);
  console.log("  Run health check:           triggerfish patrol");
  console.log("");

  return {
    configPath,
    spinePath,
    installDaemon,
    channels: channels.filter((c) => c !== "skip"),
  };
}
