/**
 * Channel and plugin add/remove operations for triggerfish.yaml.
 * @module
 */

import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { Confirm, Select } from "@cliffy/prompt";
import { backupConfig, resolveConfigPath } from "./paths.ts";
import { CHANNEL_TYPES, PLUGIN_TYPES, promptDaemonRestart } from "./config.ts";
import { promptChannelConfig, promptPluginConfig } from "./config_channel_prompts.ts";

type ChannelType = typeof CHANNEL_TYPES[number];
type PluginType = typeof PLUGIN_TYPES[number];

/**
 * Add a channel to triggerfish.yaml interactively.
 */
export async function runConfigAddChannel(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const configPath = resolveConfigPath();

  // Require interactive terminal
  if (!Deno.stdin.isTerminal()) {
    console.error("Error: add-channel requires an interactive terminal.");
    Deno.exit(1);
  }

  // Determine channel type
  let channelType: ChannelType;
  const flagType = flags.channel_type as string | undefined;

  if (flagType && CHANNEL_TYPES.includes(flagType as ChannelType)) {
    channelType = flagType as ChannelType;
  } else {
    if (flagType) {
      console.log(`Unknown channel type: ${flagType}\n`);
    }
    channelType = (await Select.prompt({
      message: "Channel type",
      options: [
        { name: "Telegram", value: "telegram" },
        { name: "Signal (via signal-cli)", value: "signal" },
        { name: "Slack", value: "slack" },
        { name: "Discord", value: "discord" },
        { name: "WhatsApp", value: "whatsapp" },
        { name: "WebChat (browser-based)", value: "webchat" },
        { name: "Email (IMAP + SMTP relay)", value: "email" },
      ],
    })) as ChannelType;
  }

  // Load existing config
  let rawYaml: string;
  try {
    rawYaml = await Deno.readTextFile(configPath);
  } catch {
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }

  const parsed = parseYaml(rawYaml) as Record<string, unknown>;
  const channels = (parsed.channels ?? {}) as Record<string, unknown>;

  // Check if channel already exists
  if (channels[channelType]) {
    const overwrite = await Confirm.prompt({
      message: `${channelType} is already configured. Overwrite?`,
      default: false,
    });
    if (!overwrite) {
      console.log("Cancelled.");
      return;
    }
  }

  console.log(`\nConfiguring ${channelType}...\n`);

  // Prompt for channel-specific fields
  const channelConfig = await promptChannelConfig(channelType);

  // Merge into config
  channels[channelType] = channelConfig;
  parsed.channels = channels;

  // Write back (with backup)
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  const content =
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
  await Deno.writeTextFile(configPath, content);

  console.log(`\n\u2713 ${channelType} added to triggerfish.yaml`);

  await promptDaemonRestart();
}

/**
 * Remove a channel from triggerfish.yaml.
 *
 * Backs up the config before writing, confirms with the user,
 * and prompts for a daemon restart if the daemon is running.
 */
export async function runConfigRemoveChannel(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const configPath = resolveConfigPath();

  // Determine channel type
  let channelType: string;
  const flagType = flags.channel_type as string | undefined;

  if (flagType && CHANNEL_TYPES.includes(flagType as ChannelType)) {
    channelType = flagType;
  } else {
    // Load config to show only configured channels
    let rawYaml: string;
    try {
      rawYaml = await Deno.readTextFile(configPath);
    } catch {
      console.error(`Config not found at ${configPath}`);
      console.error("Run 'triggerfish dive' to create initial config.");
      Deno.exit(1);
    }

    const parsed = parseYaml(rawYaml) as Record<string, unknown>;
    const channels = (parsed.channels ?? {}) as Record<string, unknown>;
    const configured = Object.keys(channels).filter((k) =>
      CHANNEL_TYPES.includes(k as ChannelType)
    );

    if (configured.length === 0) {
      console.log("No channels configured.");
      return;
    }

    if (!Deno.stdin.isTerminal()) {
      console.error(
        "Error: remove-channel requires a channel type argument in non-interactive mode.",
      );
      console.error(
        `Usage: triggerfish config remove-channel <${configured.join("|")}>`,
      );
      Deno.exit(1);
    }

    channelType = await Select.prompt({
      message: "Channel to remove",
      options: configured.map((c) => ({ name: c, value: c })),
    });
  }

  // Load config
  let rawYaml: string;
  try {
    rawYaml = await Deno.readTextFile(configPath);
  } catch {
    console.error(`Config not found at ${configPath}`);
    Deno.exit(1);
  }

  const parsed = parseYaml(rawYaml) as Record<string, unknown>;
  const channels = (parsed.channels ?? {}) as Record<string, unknown>;

  if (!channels[channelType]) {
    console.log(`Channel '${channelType}' is not configured.`);
    return;
  }

  // Confirm removal (interactive only)
  if (Deno.stdin.isTerminal()) {
    const confirm = await Confirm.prompt({
      message: `Remove ${channelType} channel configuration?`,
      default: false,
    });
    if (!confirm) {
      console.log("Cancelled.");
      return;
    }
  }

  // Remove and write back
  delete channels[channelType];
  parsed.channels = channels;

  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  const content =
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
  await Deno.writeTextFile(configPath, content);

  console.log(`\n\u2713 ${channelType} removed from triggerfish.yaml`);

  await promptDaemonRestart();
}

/**
 * Add a plugin to triggerfish.yaml interactively.
 */
export async function runConfigAddPlugin(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const configPath = resolveConfigPath();

  // Require interactive terminal
  if (!Deno.stdin.isTerminal()) {
    console.error("Error: add-plugin requires an interactive terminal.");
    Deno.exit(1);
  }

  // Determine plugin type
  let pluginType: PluginType;
  const flagType = flags.plugin_type as string | undefined;

  if (flagType && PLUGIN_TYPES.includes(flagType as PluginType)) {
    pluginType = flagType as PluginType;
  } else {
    if (flagType) {
      console.log(`Unknown plugin type: ${flagType}\n`);
    }
    pluginType = (await Select.prompt({
      message: "Plugin type",
      options: [
        { name: "Obsidian (local vault integration)", value: "obsidian" },
      ],
    })) as PluginType;
  }

  // Load existing config
  let rawYaml: string;
  try {
    rawYaml = await Deno.readTextFile(configPath);
  } catch {
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }

  const parsed = parseYaml(rawYaml) as Record<string, unknown>;
  const plugins = (parsed.plugins ?? {}) as Record<string, unknown>;

  // Check if plugin already exists
  if (plugins[pluginType]) {
    const overwrite = await Confirm.prompt({
      message: `${pluginType} is already configured. Overwrite?`,
      default: false,
    });
    if (!overwrite) {
      console.log("Cancelled.");
      return;
    }
  }

  console.log(`\nConfiguring ${pluginType}...\n`);

  // Prompt for plugin-specific fields
  const pluginConfig = await promptPluginConfig(pluginType);

  // Merge into config
  plugins[pluginType] = pluginConfig;
  parsed.plugins = plugins;

  // Write back (with backup)
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  const content =
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
  await Deno.writeTextFile(configPath, content);

  console.log(`\n\u2713 ${pluginType} plugin added to triggerfish.yaml`);

  await promptDaemonRestart();
}
