/**
 * Shared config YAML read/write utility.
 *
 * Provides Result-based config operations usable by both CLI commands
 * and LLM tool executors. CLI code calls Deno.exit() on failure;
 * tool executors return error strings. This module returns Result so
 * callers choose their own error handling.
 *
 * @module
 */

import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { backupConfig } from "../cli/config/paths.ts";
import {
  readNestedYamlValue,
  writeNestedYamlValue,
} from "../cli/config/yaml_paths.ts";
import type { Result } from "./types/classification.ts";

/** Standard YAML header prepended to every config write. */
const CONFIG_HEADER =
  "# Triggerfish Configuration\n# Generated by triggerfish dive\n\n";

/**
 * Read and parse triggerfish.yaml from disk.
 *
 * @returns Parsed config object or error string
 */
export function readConfigYaml(
  configPath: string,
): Result<Record<string, unknown>, string> {
  let rawYaml: string;
  try {
    rawYaml = Deno.readTextFileSync(configPath);
  } catch {
    return {
      ok: false,
      error:
        `Config not found at ${configPath}. Run 'triggerfish dive' to create initial config.`,
    };
  }
  try {
    const parsed = parseYaml(rawYaml);
    if (typeof parsed !== "object" || parsed === null) {
      return { ok: false, error: "Config file did not parse to an object." };
    }
    return { ok: true, value: parsed as Record<string, unknown> };
  } catch (err: unknown) {
    return {
      ok: false,
      error: `YAML parse error: ${
        err instanceof Error ? err.message : String(err)
      }`,
    };
  }
}

/**
 * Write a config object to triggerfish.yaml with backup.
 *
 * Creates a timestamped backup before overwriting.
 */
export async function writeConfigYaml(
  configPath: string,
  data: Record<string, unknown>,
): Promise<Result<void, string>> {
  try {
    await backupConfig(configPath);
    const yaml = stringifyYaml(data);
    await Deno.writeTextFile(configPath, CONFIG_HEADER + yaml);
    return { ok: true, value: undefined };
  } catch (err: unknown) {
    return {
      ok: false,
      error: `Config write failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    };
  }
}

/**
 * Read a single value from config by dotted key path.
 */
export function readConfigValue(
  configPath: string,
  key: string,
): Result<unknown, string> {
  const configResult = readConfigYaml(configPath);
  if (!configResult.ok) return configResult;
  const value = readNestedYamlValue(configResult.value, key);
  return { ok: true, value };
}

/**
 * Write a single value to config by dotted key path.
 *
 * Reads the existing config, sets the nested value, and writes back
 * with backup.
 */
export async function writeConfigValue(
  configPath: string,
  key: string,
  value: unknown,
): Promise<Result<void, string>> {
  const configResult = readConfigYaml(configPath);
  if (!configResult.ok) return configResult;
  writeNestedYamlValue(configResult.value, key, value);
  return await writeConfigYaml(configPath, configResult.value);
}

/**
 * Delete a key from config by dotted key path.
 *
 * Reads the existing config, removes the nested key, and writes back
 * with backup.
 */
export async function deleteConfigValue(
  configPath: string,
  key: string,
): Promise<Result<void, string>> {
  const configResult = readConfigYaml(configPath);
  if (!configResult.ok) return configResult;

  const parts = key.split(".");
  // deno-lint-ignore no-explicit-any
  let current: any = configResult.value;
  for (let i = 0; i < parts.length - 1; i++) {
    if (
      current === undefined || current === null ||
      typeof current !== "object"
    ) {
      return { ok: true, value: undefined }; // Path doesn't exist, nothing to delete
    }
    current = current[parts[i]];
  }
  if (
    current !== undefined && current !== null && typeof current === "object"
  ) {
    delete current[parts[parts.length - 1]];
  }
  return await writeConfigYaml(configPath, configResult.value);
}
