#!/usr/bin/env -S deno run --allow-run --allow-write
/**
 * Reads the latest git tag and writes src/_version.gen.ts.
 *
 * Run automatically by `deno task dev` and `deno task compile`.
 */

const cmd = new Deno.Command("git", {
  args: ["describe", "--tags", "--abbrev=0"],
  stdout: "piped",
  stderr: "piped",
});
const output = cmd.outputSync();

let version = "dev";
if (output.success) {
  const tag = new TextDecoder().decode(output.stdout).trim();
  version = tag.startsWith("v") ? tag.slice(1) : tag;
}

const outPath = new URL("../src/_version.gen.ts", import.meta.url).pathname;
Deno.writeTextFileSync(
  outPath,
  `// Auto-generated by scripts/stamp_version.ts — do not edit\nexport const VERSION = "${version}";\n`,
);
