/**
 * Channel and plugin add/remove operations for triggerfish.yaml.
 * @module
 */

import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { Confirm, Select } from "@cliffy/prompt";
import { backupConfig, resolveConfigPath } from "./paths.ts";
import { CHANNEL_TYPES, PLUGIN_TYPES } from "./yaml_paths.ts";
import { promptDaemonRestart } from "./config_crud.ts";
import { promptChannelConfig, promptPluginConfig } from "./channel_prompts.ts";

type ChannelType = typeof CHANNEL_TYPES[number];
type PluginType = typeof PLUGIN_TYPES[number];

/** Load and parse config YAML, exiting if not found. */
async function loadConfigYamlFile(
  configPath: string,
): Promise<Record<string, unknown>> {
  let rawYaml: string;
  try {
    rawYaml = await Deno.readTextFile(configPath);
  } catch {
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }
  return parseYaml(rawYaml) as Record<string, unknown>;
}

/** Write config YAML with backup and standard header. */
async function writeConfigYamlFile(
  configPath: string,
  parsed: Record<string, unknown>,
): Promise<void> {
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  await Deno.writeTextFile(
    configPath,
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`,
  );
}

/** Prompt for channel type from flag or interactive select. */
async function selectChannelType(
  flagType: string | undefined,
): Promise<ChannelType> {
  if (flagType && CHANNEL_TYPES.includes(flagType as ChannelType)) {
    return flagType as ChannelType;
  }
  if (flagType) console.log(`Unknown channel type: ${flagType}\n`);
  return (await Select.prompt({
    message: "Channel type",
    options: [
      { name: "Telegram", value: "telegram" },
      { name: "Signal (via signal-cli)", value: "signal" },
      { name: "Slack", value: "slack" },
      { name: "Discord", value: "discord" },
      { name: "WhatsApp", value: "whatsapp" },
      { name: "WebChat (browser-based)", value: "webchat" },
      { name: "Email (IMAP + SMTP relay)", value: "email" },
    ],
  })) as ChannelType;
}

/** Check if existing config entry exists and confirm overwrite. */
async function confirmOverwrite(
  existing: unknown,
  typeName: string,
): Promise<boolean> {
  if (!existing) return true;
  const overwrite = await Confirm.prompt({
    message: `${typeName} is already configured. Overwrite?`,
    default: false,
  });
  if (!overwrite) {
    console.log("Cancelled.");
    return false;
  }
  return true;
}

/**
 * Add a channel to triggerfish.yaml interactively.
 */
export async function runConfigAddChannel(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  if (!Deno.stdin.isTerminal()) {
    console.error("Error: add-channel requires an interactive terminal.");
    Deno.exit(1);
  }

  const configPath = resolveConfigPath();
  const channelType = await selectChannelType(
    flags.channel_type as string | undefined,
  );
  const parsed = await loadConfigYamlFile(configPath);
  const channels = (parsed.channels ?? {}) as Record<string, unknown>;

  if (!(await confirmOverwrite(channels[channelType], channelType))) return;

  console.log(`\nConfiguring ${channelType}...\n`);
  channels[channelType] = await promptChannelConfig(channelType);
  parsed.channels = channels;

  await writeConfigYamlFile(configPath, parsed);
  console.log(`\n\u2713 ${channelType} added to triggerfish.yaml`);
  await promptDaemonRestart();
}

/**
 * Remove a channel from triggerfish.yaml.
 *
 * Backs up the config before writing, confirms with the user,
 * and prompts for a daemon restart if the daemon is running.
 */
/** Select channel to remove from flags or interactive prompt. */
async function selectChannelToRemove(
  flagType: string | undefined,
  configPath: string,
): Promise<string | null> {
  if (flagType && CHANNEL_TYPES.includes(flagType as ChannelType)) {
    return flagType;
  }

  const parsed = await loadConfigYamlFile(configPath);
  const channels = (parsed.channels ?? {}) as Record<string, unknown>;
  const configured = Object.keys(channels).filter((k) =>
    CHANNEL_TYPES.includes(k as ChannelType)
  );

  if (configured.length === 0) {
    console.log("No channels configured.");
    return null;
  }
  if (!Deno.stdin.isTerminal()) {
    console.error(
      "Error: remove-channel requires a channel type argument in non-interactive mode.",
    );
    console.error(
      `Usage: triggerfish config remove-channel <${configured.join("|")}>`,
    );
    Deno.exit(1);
  }
  return Select.prompt({
    message: "Channel to remove",
    options: configured.map((c) => ({ name: c, value: c })),
  });
}

/**
 * Remove a channel from triggerfish.yaml.
 */
export async function runConfigRemoveChannel(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const configPath = resolveConfigPath();
  const channelType = await selectChannelToRemove(
    flags.channel_type as string | undefined,
    configPath,
  );
  if (channelType === null) return;

  const parsed = await loadConfigYamlFile(configPath);
  const channels = (parsed.channels ?? {}) as Record<string, unknown>;

  if (!channels[channelType]) {
    console.log(`Channel '${channelType}' is not configured.`);
    return;
  }

  if (Deno.stdin.isTerminal()) {
    const confirm = await Confirm.prompt({
      message: `Remove ${channelType} channel configuration?`,
      default: false,
    });
    if (!confirm) {
      console.log("Cancelled.");
      return;
    }
  }

  delete channels[channelType];
  parsed.channels = channels;
  await writeConfigYamlFile(configPath, parsed);
  console.log(`\n\u2713 ${channelType} removed from triggerfish.yaml`);
  await promptDaemonRestart();
}

/**
 * Add a plugin to triggerfish.yaml interactively.
 */
/** Prompt for plugin type from flag or interactive select. */
async function selectPluginType(
  flagType: string | undefined,
): Promise<PluginType> {
  if (flagType && PLUGIN_TYPES.includes(flagType as PluginType)) {
    return flagType as PluginType;
  }
  if (flagType) console.log(`Unknown plugin type: ${flagType}\n`);
  return (await Select.prompt({
    message: "Plugin type",
    options: [
      { name: "Obsidian (local vault integration)", value: "obsidian" },
    ],
  })) as PluginType;
}

/**
 * Add a plugin to triggerfish.yaml interactively.
 */
export async function runConfigAddPlugin(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  if (!Deno.stdin.isTerminal()) {
    console.error("Error: add-plugin requires an interactive terminal.");
    Deno.exit(1);
  }

  const configPath = resolveConfigPath();
  const pluginType = await selectPluginType(
    flags.plugin_type as string | undefined,
  );
  const parsed = await loadConfigYamlFile(configPath);
  const plugins = (parsed.plugins ?? {}) as Record<string, unknown>;

  if (!(await confirmOverwrite(plugins[pluginType], pluginType))) return;

  console.log(`\nConfiguring ${pluginType}...\n`);
  plugins[pluginType] = await promptPluginConfig(pluginType);
  parsed.plugins = plugins;

  await writeConfigYamlFile(configPath, parsed);
  console.log(`\n\u2713 ${pluginType} plugin added to triggerfish.yaml`);
  await promptDaemonRestart();
}
