/**
 * Config CRUD operations — set, get, validate commands for triggerfish.yaml.
 *
 * Also provides the daemon restart prompt shared by config set,
 * add-channel, and add-plugin commands.
 * @module
 */

import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { Confirm } from "@cliffy/prompt";
import { backupConfig, resolveConfigPath } from "./paths.ts";
import { getDaemonStatus, restartDaemon } from "../daemon/daemon.ts";
import { validateConfig } from "../../core/config.ts";
import { readNestedYamlValue, writeNestedYamlValue } from "./yaml_paths.ts";
import { createLogger } from "../../core/logger/mod.ts";

const log = createLogger("cli.config");

// ─── Daemon restart ─────────────────────────────────────────────

/**
 * Prompt the user to restart the daemon if it's running.
 * Shared by config set, add-channel, and add-plugin commands.
 */
export async function promptDaemonRestart(): Promise<void> {
  const status = await getDaemonStatus();
  if (status.running) {
    const restart = await Confirm.prompt({
      message: "Restart daemon to apply?",
      default: true,
    });
    if (restart) {
      const result = await restartDaemon(Deno.execPath());
      if (result.ok) {
        console.log("✓ Daemon restarted");
      } else {
        log.warn("Daemon restart failed after config change", {
          operation: "promptDaemonRestart",
          message: result.message,
        });
        console.log(`✗ ${result.message}`);
      }
    }
  } else {
    console.log("Daemon is not running. Start it with: triggerfish start");
  }
}

// ─── Helpers ────────────────────────────────────────────────────

/** Coerce a string value to boolean or number if applicable. */
function coerceConfigValue(rawValue: string): unknown {
  if (rawValue === "true") return true;
  if (rawValue === "false") return false;
  if (/^\d+$/.test(rawValue)) return parseInt(rawValue, 10);
  return rawValue;
}

/** Mask secret values for display, showing only first and last 4 chars. */
function maskSecretDisplay(
  key: string,
  rawValue: string,
  coerced: unknown,
): string {
  if (key.includes("key") || key.includes("secret") || key.includes("token")) {
    return `${rawValue.slice(0, 4)}...${rawValue.slice(-4)}`;
  }
  return String(coerced);
}

/** Read and parse the config YAML, exiting with error if not found. */
function readConfigYaml(configPath: string): Record<string, unknown> {
  let rawYaml: string;
  try {
    rawYaml = Deno.readTextFileSync(configPath);
  } catch (err: unknown) {
    log.error("Configuration file not found", {
      operation: "readConfigYaml",
      configPath,
      err,
    });
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }
  return parseYaml(rawYaml) as Record<string, unknown>;
}

// ─── Set ────────────────────────────────────────────────────────

/**
 * Set a config value in triggerfish.yaml by dotted key path.
 */
export async function runConfigSet(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const key = flags["config_key"] as string | undefined;
  const rawValue = flags["config_value"] as string | undefined;
  if (!key || rawValue === undefined) {
    console.error("Usage: triggerfish config set <key> <value>");
    Deno.exit(1);
  }

  const configPath = resolveConfigPath();
  const parsed = readConfigYaml(configPath);
  const value = coerceConfigValue(rawValue);

  writeNestedYamlValue(parsed, key, value);
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  await Deno.writeTextFile(
    configPath,
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`,
  );

  console.log(`\n  ${key} = ${maskSecretDisplay(key, rawValue, value)}\n`);
  await promptDaemonRestart();
}

// ─── Get ────────────────────────────────────────────────────────

/**
 * Get a config value from triggerfish.yaml by dotted key path.
 */
export function runConfigGet(
  flags: Readonly<Record<string, boolean | string>>,
): void {
  const key = flags["config_key"] as string | undefined;
  if (!key) {
    console.error("Usage: triggerfish config get <key>");
    Deno.exit(1);
  }

  const parsed = readConfigYaml(resolveConfigPath());
  const value = readNestedYamlValue(parsed, key);

  if (value === undefined) {
    console.log(`\n  ${key} is not set\n`);
  } else {
    console.log(
      `\n  ${key} = ${maskSecretDisplay(key, String(value), value)}\n`,
    );
  }
}

// ─── Validate ───────────────────────────────────────────────────

/** Parse raw YAML text into an object, exiting on syntax error. */
function parseYamlOrExit(rawYaml: string): Record<string, unknown> {
  let parsed: unknown;
  try {
    parsed = parseYaml(rawYaml);
  } catch (err) {
    log.error("Configuration YAML parse failed", {
      operation: "parseConfig",
      err,
    });
    console.error(
      `\n  YAML parse error: ${
        err instanceof Error ? err.message : String(err)
      }\n`,
    );
    Deno.exit(1);
  }

  if (typeof parsed !== "object" || parsed === null) {
    log.error("Configuration file did not parse to an object", {
      operation: "parseConfig",
    });
    console.error("\n  Config file did not parse to an object.\n");
    Deno.exit(1);
  }

  return parsed as Record<string, unknown>;
}

/** Parse and structurally validate config YAML, exiting on error. */
function parseAndValidateConfigYaml(
  configPath: string,
): Record<string, unknown> {
  const rawYaml = Deno.readTextFileSync(configPath);
  const parsed = parseYamlOrExit(rawYaml);

  const result = validateConfig(parsed);
  if (!result.ok) {
    log.warn("Configuration validation failed", {
      operation: "validateConfig",
      error: result.error,
    });
    console.error(`\n  Validation error: ${result.error}\n`);
    Deno.exit(1);
  }

  return parsed;
}

/** Collect non-fatal configuration warnings. */
function collectConfigWarnings(config: Record<string, unknown>): string[] {
  const warnings: string[] = [];
  const models = config.models as Record<string, unknown> | undefined;
  if (
    models?.providers &&
    Object.keys(models.providers as Record<string, unknown>).length === 0
  ) {
    warnings.push("No LLM providers configured under models.providers");
  }
  const channels = config.channels as Record<string, unknown> | undefined;
  if (!channels || Object.keys(channels).length === 0) {
    warnings.push("No channels configured");
  }
  return warnings;
}

/**
 * Validate triggerfish.yaml and report errors.
 */
export function runConfigValidate(): void {
  const configPath = resolveConfigPath();
  const config = parseAndValidateConfigYaml(configPath);
  const warnings = collectConfigWarnings(config);

  console.log(`\n  Configuration valid: ${configPath}`);
  if (warnings.length > 0) {
    console.log("\n  Warnings:");
    for (const w of warnings) console.log(`    - ${w}`);
  }
  console.log();
}
