/**
 * CLI config command — manages triggerfish.yaml interactively.
 *
 * Core utilities (YAML path access, daemon restart prompt), CRUD operations,
 * and the command dispatcher. Channel prompts, channel/plugin add/remove,
 * and secret management are in dedicated sub-modules.
 * @module
 */

import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { Confirm } from "@cliffy/prompt";
import { backupConfig, resolveConfigPath } from "./paths.ts";
import {
  getDaemonStatus,
  installAndStartDaemon,
  stopDaemon,
} from "../daemon/daemon.ts";
import { validateConfig } from "../../core/config.ts";

// ─── Constants ───────────────────────────────────────────────────

/** Supported channel types for add-channel. */
export const CHANNEL_TYPES = [
  "telegram",
  "slack",
  "discord",
  "whatsapp",
  "webchat",
  "email",
  "signal",
] as const;

export const PLUGIN_TYPES = [
  "obsidian",
] as const;

// ─── YAML path utilities ────────────────────────────────────────

/**
 * Set a nested value in an object using a dotted key path.
 * Creates intermediate objects as needed.
 */
export function writeNestedYamlValue(
  obj: Record<string, unknown>,
  keyPath: string,
  value: unknown,
): void {
  const parts = keyPath.split(".");
  // deno-lint-ignore no-explicit-any
  let current: any = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const part = parts[i];
    if (current[part] === undefined || typeof current[part] !== "object") {
      current[part] = {};
    }
    current = current[part];
  }
  current[parts[parts.length - 1]] = value;
}

/**
 * Get a nested value from an object using a dotted key path.
 */
export function readNestedYamlValue(
  obj: Record<string, unknown>,
  keyPath: string,
): unknown {
  const parts = keyPath.split(".");
  // deno-lint-ignore no-explicit-any
  let current: any = obj;
  for (const part of parts) {
    if (
      current === undefined || current === null || typeof current !== "object"
    ) {
      return undefined;
    }
    current = current[part];
  }
  return current;
}

/**
 * Prompt the user to restart the daemon if it's running.
 * Shared by config set, add-channel, and add-plugin commands.
 */
export async function promptDaemonRestart(): Promise<void> {
  const status = await getDaemonStatus();
  if (status.running) {
    const restart = await Confirm.prompt({
      message: "Restart daemon to apply?",
      default: true,
    });
    if (restart) {
      const stopResult = await stopDaemon();
      if (!stopResult.ok) {
        console.log(`\u2717 Failed to stop daemon: ${stopResult.message}`);
        return;
      }
      const startResult = await installAndStartDaemon(Deno.execPath());
      if (startResult.ok) {
        console.log("\u2713 Daemon restarted");
      } else {
        console.log(`\u2717 ${startResult.message}`);
      }
    }
  } else {
    console.log("Daemon is not running. Start it with: triggerfish start");
  }
}

// ─── CRUD operations ────────────────────────────────────────────

/** Coerce a string value to boolean or number if applicable. */
function coerceConfigValue(rawValue: string): unknown {
  if (rawValue === "true") return true;
  if (rawValue === "false") return false;
  if (/^\d+$/.test(rawValue)) return parseInt(rawValue, 10);
  return rawValue;
}

/** Mask secret values for display, showing only first and last 4 chars. */
function maskSecretDisplay(
  key: string,
  rawValue: string,
  coerced: unknown,
): string {
  if (key.includes("key") || key.includes("secret") || key.includes("token")) {
    return `${rawValue.slice(0, 4)}...${rawValue.slice(-4)}`;
  }
  return String(coerced);
}

/** Read and parse the config YAML, exiting with error if not found. */
function readConfigYaml(configPath: string): Record<string, unknown> {
  let rawYaml: string;
  try {
    rawYaml = Deno.readTextFileSync(configPath);
  } catch {
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }
  return parseYaml(rawYaml) as Record<string, unknown>;
}

/**
 * Set a config value in triggerfish.yaml by dotted key path.
 */
export async function runConfigSet(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const key = flags["config_key"] as string | undefined;
  const rawValue = flags["config_value"] as string | undefined;
  if (!key || rawValue === undefined) {
    console.error("Usage: triggerfish config set <key> <value>");
    Deno.exit(1);
  }

  const configPath = resolveConfigPath();
  const parsed = readConfigYaml(configPath);
  const value = coerceConfigValue(rawValue);

  writeNestedYamlValue(parsed, key, value);
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  await Deno.writeTextFile(
    configPath,
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`,
  );

  console.log(`\n  ${key} = ${maskSecretDisplay(key, rawValue, value)}\n`);
  await promptDaemonRestart();
}

/**
 * Get a config value from triggerfish.yaml by dotted key path.
 */
export function runConfigGet(
  flags: Readonly<Record<string, boolean | string>>,
): void {
  const key = flags["config_key"] as string | undefined;
  if (!key) {
    console.error("Usage: triggerfish config get <key>");
    Deno.exit(1);
  }

  const parsed = readConfigYaml(resolveConfigPath());
  const value = readNestedYamlValue(parsed, key);

  if (value === undefined) {
    console.log(`\n  ${key} is not set\n`);
  } else {
    console.log(
      `\n  ${key} = ${maskSecretDisplay(key, String(value), value)}\n`,
    );
  }
}

/** Parse and structurally validate config YAML, exiting on error. */
function parseAndValidateConfigYaml(
  configPath: string,
): Record<string, unknown> {
  const rawYaml = Deno.readTextFileSync(configPath);

  let parsed: unknown;
  try {
    parsed = parseYaml(rawYaml);
  } catch (err) {
    console.error(
      `\n  YAML parse error: ${
        err instanceof Error ? err.message : String(err)
      }\n`,
    );
    Deno.exit(1);
  }

  if (typeof parsed !== "object" || parsed === null) {
    console.error("\n  Config file did not parse to an object.\n");
    Deno.exit(1);
  }

  const result = validateConfig(parsed as Record<string, unknown>);
  if (!result.ok) {
    console.error(`\n  Validation error: ${result.error}\n`);
    Deno.exit(1);
  }

  return parsed as Record<string, unknown>;
}

/** Collect non-fatal configuration warnings. */
function collectConfigWarnings(config: Record<string, unknown>): string[] {
  const warnings: string[] = [];
  const models = config.models as Record<string, unknown> | undefined;
  if (
    models?.providers &&
    Object.keys(models.providers as Record<string, unknown>).length === 0
  ) {
    warnings.push("No LLM providers configured under models.providers");
  }
  const channels = config.channels as Record<string, unknown> | undefined;
  if (!channels || Object.keys(channels).length === 0) {
    warnings.push("No channels configured");
  }
  return warnings;
}

/**
 * Validate triggerfish.yaml and report errors.
 */
export function runConfigValidate(): void {
  const configPath = resolveConfigPath();
  const config = parseAndValidateConfigYaml(configPath);
  const warnings = collectConfigWarnings(config);

  console.log(`\n  Configuration valid: ${configPath}`);
  if (warnings.length > 0) {
    console.log("\n  Warnings:");
    for (const w of warnings) console.log(`    - ${w}`);
  }
  console.log();
}

// ─── Re-exports ─────────────────────────────────────────────────

export { promptChannelConfig, promptPluginConfig } from "./channel_prompts.ts";
export {
  runConfigAddChannel,
  runConfigAddPlugin,
  runConfigRemoveChannel,
} from "./channels.ts";
export {
  runConfigGetSecret,
  runConfigMigrateSecrets,
  runConfigSetSecret,
} from "./secrets.ts";

// ─── Dispatcher ─────────────────────────────────────────────────

/**
 * Config command dispatcher.
 */
export async function runConfig(
  subcommand: string | undefined,
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  switch (subcommand) {
    case "add-channel": {
      const { runConfigAddChannel } = await import("./channels.ts");
      await runConfigAddChannel(flags);
      break;
    }
    case "remove-channel": {
      const { runConfigRemoveChannel } = await import("./channels.ts");
      await runConfigRemoveChannel(flags);
      break;
    }
    case "add-plugin": {
      const { runConfigAddPlugin } = await import("./channels.ts");
      await runConfigAddPlugin(flags);
      break;
    }
    case "set":
      await runConfigSet(flags);
      break;
    case "get":
      runConfigGet(flags);
      break;
    case "validate":
      runConfigValidate();
      break;
    case "set-secret": {
      const { runConfigSetSecret } = await import("./secrets.ts");
      await runConfigSetSecret(flags);
      break;
    }
    case "get-secret": {
      const { runConfigGetSecret } = await import("./secrets.ts");
      await runConfigGetSecret(flags);
      break;
    }
    case "migrate-secrets": {
      const { runConfigMigrateSecrets } = await import("./secrets.ts");
      await runConfigMigrateSecrets();
      break;
    }
    default:
      console.log(`
CONFIG USAGE:
  triggerfish config set <key> <value>    Set a configuration value
  triggerfish config get <key>            Get a configuration value
  triggerfish config validate             Validate configuration
  triggerfish config add-channel [type]      Add a channel interactively
  triggerfish config remove-channel [type]   Remove a channel
  triggerfish config add-plugin [name]       Add a plugin interactively
  triggerfish config set-secret <key> <value>  Store a secret in OS keychain
  triggerfish config get-secret <key>          Retrieve a secret from OS keychain
  triggerfish config migrate-secrets           Migrate plaintext secrets to keychain

KEYS use dotted paths into triggerfish.yaml:
  web.search.provider              Search provider (brave)
  web.search.api_key               Search API key
  models.primary.provider          Primary provider name
  models.primary.model             Primary model name
  models.providers.<name>.apiKey   Provider API key
  scheduler.trigger.enabled        Enable trigger wakeups
  plugins.obsidian.vault_path      Obsidian vault path
  plugins.obsidian.classification  Vault classification level

CHANNEL TYPES:
  telegram, slack, discord, whatsapp, webchat, email

PLUGIN TYPES:
  obsidian

EXAMPLES:
  triggerfish config set models.primary.model claude-sonnet
  triggerfish config set web.search.provider brave
  triggerfish config set web.search.api_key sk-abc123
  triggerfish config set scheduler.trigger.enabled true
  triggerfish config get models.primary.model
  triggerfish config add-channel telegram
  triggerfish config remove-channel signal
  triggerfish config add-plugin obsidian
  triggerfish config set-secret github-pat ghp_...
  triggerfish config get-secret github-pat
  triggerfish config migrate-secrets
`);
      break;
  }
}
