/**
 * MCP server CLI config commands — add, remove, list.
 *
 * Interactive prompts for adding MCP servers via the CLI.
 * @module
 */

import { Input, Select } from "@cliffy/prompt";
import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { backupConfig, resolveConfigPath } from "./paths.ts";
import { promptDaemonRestart } from "./config_crud.ts";
import { createLogger } from "../../core/logger/mod.ts";

const log = createLogger("cli.config.mcp");

/** Classification options for interactive prompt. */
const CLASSIFICATION_OPTIONS = [
  { name: "PUBLIC", value: "PUBLIC" },
  { name: "INTERNAL (default)", value: "INTERNAL" },
  { name: "CONFIDENTIAL", value: "CONFIDENTIAL" },
  { name: "RESTRICTED", value: "RESTRICTED" },
];

/** Load and parse config YAML, exiting if not found. */
async function loadConfig(
  configPath: string,
): Promise<Record<string, unknown>> {
  let rawYaml: string;
  try {
    rawYaml = await Deno.readTextFile(configPath);
  } catch (err: unknown) {
    log.error("Configuration file not found", {
      operation: "loadMcpConfig",
      configPath,
      err,
    });
    console.error(`Config not found at ${configPath}`);
    console.error("Run 'triggerfish dive' to create initial config.");
    Deno.exit(1);
  }
  return parseYaml(rawYaml) as Record<string, unknown>;
}

/** Write config back with backup and header. */
async function saveConfig(
  configPath: string,
  parsed: Record<string, unknown>,
): Promise<void> {
  await backupConfig(configPath);
  const yaml = stringifyYaml(parsed);
  await Deno.writeTextFile(
    configPath,
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`,
  );
}

/** Prompt for transport type. */
async function promptTransport(): Promise<"stdio" | "sse"> {
  return (await Select.prompt({
    message: "Transport type",
    options: [
      { name: "stdio (command-based)", value: "stdio" },
      { name: "SSE (HTTP URL)", value: "sse" },
    ],
  })) as "stdio" | "sse";
}

/** Prompt for environment variables. */
async function promptEnvVars(): Promise<Record<string, string> | undefined> {
  const envVars: Record<string, string> = {};
  const addEnv = await Select.prompt({
    message: "Add environment variables?",
    options: [
      { name: "No", value: "no" },
      { name: "Yes", value: "yes" },
    ],
  });
  if (addEnv === "no") return undefined;

  while (true) {
    const key = await Input.prompt({
      message: "Env var name (empty to finish)",
    });
    if (!key) break;
    const value = await Input.prompt({
      message: `Value for ${key} (use 'secret:<name>' for keychain refs)`,
    });
    envVars[key] = value;
  }
  return Object.keys(envVars).length > 0 ? envVars : undefined;
}

/**
 * Add an MCP server to triggerfish.yaml interactively.
 */
export async function addMcpServerInteractive(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  if (!Deno.stdin.isTerminal()) {
    console.error("Error: add-mcp requires an interactive terminal.");
    Deno.exit(1);
  }

  const configPath = resolveConfigPath();
  const parsed = await loadConfig(configPath);

  const serverId = (flags.server_id as string) || await Input.prompt({
    message: "Server ID (unique name)",
    validate: (v) => v.length > 0 || "Server ID is required",
  });

  const mcp = (parsed.mcp ?? {}) as Record<string, unknown>;
  const servers = (mcp.servers ?? {}) as Record<string, unknown>;

  if (servers[serverId]) {
    console.log(`Server '${serverId}' already exists. Use remove-mcp first.`);
    return;
  }

  const transport = await promptTransport();
  const serverConfig: Record<string, unknown> = {};

  if (transport === "stdio") {
    serverConfig.command = await Input.prompt({
      message: "Command (e.g. npx, node, uvx, deno)",
      validate: (v) => v.length > 0 || "Command is required",
    });
    const argsStr = await Input.prompt({
      message: "Arguments (space-separated)",
    });
    if (argsStr.trim()) {
      serverConfig.args = argsStr.trim().split(/\s+/);
    }
  } else {
    serverConfig.url = await Input.prompt({
      message: "SSE URL (e.g. http://localhost:3000/sse)",
      validate: (v) => v.length > 0 || "URL is required",
    });
  }

  const classification = await Select.prompt({
    message: "Classification level",
    options: CLASSIFICATION_OPTIONS,
    default: "INTERNAL",
  });
  serverConfig.classification = classification;
  serverConfig.enabled = true;

  const env = await promptEnvVars();
  if (env) serverConfig.env = env;

  servers[serverId] = serverConfig;
  mcp.servers = servers;
  parsed.mcp = mcp;

  await saveConfig(configPath, parsed);
  console.log(`\n\u2713 MCP server '${serverId}' added to triggerfish.yaml`);
  await promptDaemonRestart();
}

/**
 * Remove an MCP server from triggerfish.yaml.
 */
export async function removeMcpServerInteractive(
  flags: Readonly<Record<string, boolean | string>>,
): Promise<void> {
  const configPath = resolveConfigPath();
  const parsed = await loadConfig(configPath);
  const mcp = (parsed.mcp ?? {}) as Record<string, unknown>;
  const servers = (mcp.servers ?? {}) as Record<string, unknown>;
  const serverIds = Object.keys(servers);

  if (serverIds.length === 0) {
    console.log("No MCP servers configured.");
    return;
  }

  let serverId = flags.server_id as string | undefined;
  if (!serverId) {
    if (!Deno.stdin.isTerminal()) {
      console.error(
        "Error: remove-mcp requires a server_id in non-interactive mode.",
      );
      console.error(
        `Usage: triggerfish config remove-mcp <${serverIds.join("|")}>`,
      );
      Deno.exit(1);
    }
    serverId = await Select.prompt({
      message: "Server to remove",
      options: serverIds.map((id) => ({ name: id, value: id })),
    });
  }

  if (!servers[serverId]) {
    console.log(`MCP server '${serverId}' is not configured.`);
    return;
  }

  delete servers[serverId];
  mcp.servers = servers;
  parsed.mcp = mcp;

  await saveConfig(configPath, parsed);
  console.log(
    `\n\u2713 MCP server '${serverId}' removed from triggerfish.yaml`,
  );
  await promptDaemonRestart();
}

/**
 * List configured MCP servers.
 */
export async function listMcpServersInteractive(): Promise<void> {
  const configPath = resolveConfigPath();
  const parsed = await loadConfig(configPath);
  const mcp = (parsed.mcp ?? {}) as Record<string, unknown>;
  const servers = (mcp.servers ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const serverIds = Object.keys(servers);

  if (serverIds.length === 0) {
    console.log("\n  No MCP servers configured.\n");
    return;
  }

  console.log(`\n  MCP Servers (${serverIds.length}):\n`);
  for (const id of serverIds) {
    const cfg = servers[id];
    const transport = cfg.command ? `stdio: ${cfg.command}` : `sse: ${cfg.url}`;
    const classification = cfg.classification ?? "INTERNAL";
    const enabled = cfg.enabled !== false ? "enabled" : "disabled";
    console.log(`    ${id}`);
    console.log(`      Transport: ${transport}`);
    if (cfg.args) {
      console.log(`      Args: ${(cfg.args as string[]).join(" ")}`);
    }
    console.log(`      Classification: ${classification}`);
    console.log(`      Status: ${enabled}`);
    console.log();
  }
}
