/**
 * Re-exports the build-stamped version.
 *
 * The file `_version.gen.ts` is generated by `scripts/stamp_version.ts`
 * (run automatically by `deno task dev` and `deno task compile`).
 * Git tags are the single source of truth for the version number.
 *
 * @module
 */

export { VERSION } from "./_version.gen.ts";
