/**
 * Selective reconfiguration wizard — lets the user choose which
 * sections to update while preserving existing config.
 *
 * @module
 */

import { Checkbox } from "@cliffy/prompt";
import { join } from "@std/path";
import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { createLogger } from "../../core/logger/mod.ts";

const log = createLogger("dive");

import { launchInteractiveWizard } from "../wizard/wizard.ts";
import {
  applyAllSections,
  type SelectiveWizardState,
} from "./wizard_selective_sections.ts";

import type { DiveResult, WizardSection } from "../wizard/wizard_types.ts";

// ── Config file I/O ───────────────────────────────────────────────────────────

/** Load existing YAML config from disk, returning null on failure. */
async function loadExistingConfig(
  configPath: string,
): Promise<Record<string, unknown> | null> {
  try {
    const raw = await Deno.readTextFile(configPath);
    return (parseYaml(raw) as Record<string, unknown> | null) ?? {};
  } catch {
    return null;
  }
}

/** Load existing SPINE.md content from disk. */
async function loadExistingSpine(spinePath: string): Promise<string> {
  try {
    return await Deno.readTextFile(spinePath);
  } catch {
    return "";
  }
}

/** Write the final merged config to triggerfish.yaml. */
async function writeUpdatedConfig(
  configPath: string,
  config: Record<string, unknown>,
): Promise<void> {
  const yaml = stringifyYaml(config as Record<string, unknown>);
  const content =
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
  await Deno.writeTextFile(configPath, content);
  console.log("");
  console.log(`  \u2713 Updated: ${configPath}`);
  console.log("");
}

// ── Section selection ─────────────────────────────────────────────────────────

/** Print the reconfiguration header banner. */
function printReconfigurationBanner(): void {
  console.log("");
  console.log("  Reconfigure Triggerfish");
  console.log("  ======================");
  console.log("");
  console.log("  Select which sections you want to change.");
  console.log("  Unselected sections will keep their current settings.");
  console.log("");
}

/** Prompt the user to choose which sections to update. */
async function promptSectionSelection(): Promise<WizardSection[]> {
  printReconfigurationBanner();
  return (await Checkbox.prompt({
    message: "Which sections do you want to update?",
    options: [
      { name: "LLM Provider (model, API key)", value: "llm" },
      { name: "Per-Classification Models", value: "classification_models" },
      { name: "Agent Name & Personality (SPINE.md)", value: "agent" },
      {
        name: "Channels (Telegram, Discord, Signal, WebChat)",
        value: "channels",
      },
      { name: "Plugins (Obsidian)", value: "plugins" },
      { name: "Google Workspace", value: "google" },
      { name: "GitHub", value: "github" },
      { name: "Search Provider", value: "search" },
      { name: "Daemon Settings", value: "daemon" },
    ],
  })) as WizardSection[];
}

// ── Classification defaults ───────────────────────────────────────────────────

/** Ensure the config has classification defaults set. */
function ensureClassificationDefaults(config: Record<string, unknown>): void {
  if (!config["classification"]) {
    config["classification"] = { mode: "personal", levels: "standard" };
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Build the unchanged-config result when no sections are selected. */
function buildUnchangedResult(
  configPath: string,
  spinePath: string,
): DiveResult {
  console.log("");
  console.log("  No sections selected \u2014 config unchanged.");
  console.log("");
  return { configPath, spinePath, installDaemon: false, channels: [] };
}

/** Enforce that stdin is an interactive terminal. */
function enforceTerminalRequirement(): void {
  if (!Deno.stdin.isTerminal()) {
    log.error("Terminal requirement not met", {
      operation: "enforceTerminalRequirement",
      reason: "stdin is not a TTY",
    });
    console.error("");
    console.error("  Error: the dive wizard requires an interactive terminal.");
    console.error("");
    Deno.exit(1);
  }
}

/** Create the initial wizard state from loaded config and selected sections. */
function createWizardState(options: {
  sections: WizardSection[];
  existingConfig: Record<string, unknown>;
  existingSpine: string;
  spinePath: string;
}): SelectiveWizardState {
  return {
    sections: options.sections,
    config: { ...options.existingConfig },
    existingConfig: options.existingConfig,
    existingSpine: options.existingSpine,
    spinePath: options.spinePath,
    activeChannels: [],
    installDaemon: false,
  };
}

/** Build the final DiveResult from completed wizard state. */
function buildSelectiveResult(
  state: SelectiveWizardState,
  configPath: string,
  spinePath: string,
): DiveResult {
  return {
    configPath,
    spinePath,
    installDaemon: state.installDaemon,
    channels: state.activeChannels,
  };
}

// ── Public entry point ────────────────────────────────────────────────────────

/**
 * Run a selective dive wizard that lets the user choose which sections to
 * reconfigure while preserving the rest of their existing config.
 */
export async function launchSelectiveWizard(
  baseDir: string,
): Promise<DiveResult> {
  const configPath = join(baseDir, "triggerfish.yaml");
  const spinePath = join(baseDir, "SPINE.md");
  enforceTerminalRequirement();

  const existingConfig = await loadExistingConfig(configPath);
  if (existingConfig === null) return launchInteractiveWizard(baseDir);

  const existingSpine = await loadExistingSpine(spinePath);
  const sections = await promptSectionSelection();
  if (sections.length === 0) return buildUnchangedResult(configPath, spinePath);

  const state = createWizardState({
    sections,
    existingConfig,
    existingSpine,
    spinePath,
  });
  await applyAllSections(state);
  ensureClassificationDefaults(state.config);
  await writeUpdatedConfig(configPath, state.config);

  return buildSelectiveResult(state, configPath, spinePath);
}

/** @deprecated Use launchSelectiveWizard instead */
export const runWizardSelective = launchSelectiveWizard;
