/**
 * Selective reconfiguration wizard — lets the user choose which
 * sections to update while preserving existing config.
 *
 * @module
 */

import { Checkbox, Confirm } from "@cliffy/prompt";
import { join } from "@std/path";
import { parse as parseYaml, stringify as stringifyYaml } from "@std/yaml";
import { createLogger } from "../../core/logger/mod.ts";

const log = createLogger("dive");

import { runWizard } from "../wizard/wizard.ts";
import { reconfigureLlmProvider } from "./selective_llm.ts";
import { reconfigureAgentIdentity } from "./selective_identity.ts";
import { reconfigureChannels } from "./selective_channels.ts";
import { reconfigurePlugins } from "./selective_plugins.ts";
import { reconfigureSearchProvider } from "./selective_search.ts";
import { reconfigureClassificationModels } from "./selective_classification_models.ts";

import type { DiveResult, WizardSection } from "../wizard/wizard_types.ts";

// ── Mutable reconfiguration state ─────────────────────────────────────────────

/** Accumulated state during selective reconfiguration. */
interface SelectiveWizardState {
  readonly sections: WizardSection[];
  config: Record<string, unknown>;
  readonly existingConfig: Record<string, unknown>;
  readonly existingSpine: string;
  readonly spinePath: string;
  activeChannels: string[];
  installDaemon: boolean;
}

// ── Config file I/O ───────────────────────────────────────────────────────────

/** Load existing YAML config from disk, returning null on failure. */
async function loadExistingConfig(
  configPath: string,
): Promise<Record<string, unknown> | null> {
  try {
    const raw = await Deno.readTextFile(configPath);
    return (parseYaml(raw) as Record<string, unknown> | null) ?? {};
  } catch {
    return null;
  }
}

/** Load existing SPINE.md content from disk. */
async function loadExistingSpine(spinePath: string): Promise<string> {
  try {
    return await Deno.readTextFile(spinePath);
  } catch {
    return "";
  }
}

/** Write the final merged config to triggerfish.yaml. */
async function writeUpdatedConfig(
  configPath: string,
  config: Record<string, unknown>,
): Promise<void> {
  const yaml = stringifyYaml(config as Record<string, unknown>);
  const content =
    `# Triggerfish Configuration\n# Generated by triggerfish dive\n\n${yaml}`;
  await Deno.writeTextFile(configPath, content);
  console.log("");
  console.log(`  \u2713 Updated: ${configPath}`);
  console.log("");
}

// ── Section selection ─────────────────────────────────────────────────────────

/** Print the reconfiguration header banner. */
function printReconfigurationBanner(): void {
  console.log("");
  console.log("  Reconfigure Triggerfish");
  console.log("  ======================");
  console.log("");
  console.log("  Select which sections you want to change.");
  console.log("  Unselected sections will keep their current settings.");
  console.log("");
}

/** Prompt the user to choose which sections to update. */
async function promptSectionSelection(): Promise<WizardSection[]> {
  printReconfigurationBanner();
  return (await Checkbox.prompt({
    message: "Which sections do you want to update?",
    options: [
      { name: "LLM Provider (model, API key)", value: "llm" },
      { name: "Per-Classification Models", value: "classification_models" },
      { name: "Agent Name & Personality (SPINE.md)", value: "agent" },
      { name: "Channels (Telegram, Discord, Signal, WebChat)", value: "channels" },
      { name: "Plugins (Obsidian)", value: "plugins" },
      { name: "Google Workspace", value: "google" },
      { name: "GitHub", value: "github" },
      { name: "Search Provider", value: "search" },
      { name: "Daemon Settings", value: "daemon" },
    ],
  })) as WizardSection[];
}

// ── Individual section dispatchers ────────────────────────────────────────────

/** Apply the LLM provider reconfiguration if selected. */
async function applyLlmSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("llm")) return;
  state.config["models"] = await reconfigureLlmProvider(state.existingConfig);
}

/** Apply the classification models reconfiguration if selected. */
async function applyClassificationModelsSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("classification_models")) return;
  const models = state.config["models"] as Record<string, unknown> | undefined;
  if (!models) return;
  const result = await reconfigureClassificationModels(state.existingConfig);
  if (result) {
    models["classification_models"] = result;
  } else {
    delete models["classification_models"];
  }
}

/** Apply the agent identity reconfiguration if selected. */
async function applyAgentSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("agent")) return;
  await reconfigureAgentIdentity(state.existingSpine, state.spinePath);
}

/** Apply the channel reconfiguration if selected. */
async function applyChannelsSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("channels")) return;
  state.config["channels"] = await reconfigureChannels(
    state.existingConfig,
    state.activeChannels,
  );
}

/** Apply the plugin reconfiguration if selected. */
async function applyPluginsSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("plugins")) return;
  const pluginsResult = await reconfigurePlugins(state.existingConfig);
  if (pluginsResult) {
    state.config["plugins"] = pluginsResult;
  } else {
    delete state.config["plugins"];
  }
}

/** Prompt for Google Workspace reconnection if selected. */
async function applyGoogleSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("google")) return;
  console.log("");
  console.log("  Google Workspace");
  console.log("");
  const connect = await Confirm.prompt({ message: "Connect a Google account?", default: false });
  console.log(connect ? "\n  Run: triggerfish connect google" : "  \u2192 Skipped.");
}

/** Prompt for GitHub reconnection if selected. */
async function applyGitHubSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("github")) return;
  console.log("");
  console.log("  GitHub");
  console.log("");
  const connect = await Confirm.prompt({ message: "Connect a GitHub account?", default: false });
  console.log(connect ? "\n  Run: triggerfish connect github" : "  \u2192 Skipped.");
}

/** Apply the search provider reconfiguration if selected. */
async function applySearchSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("search")) return;
  const webResult = await reconfigureSearchProvider(state.existingConfig);
  if (webResult) {
    state.config["web"] = webResult;
  } else {
    delete state.config["web"];
  }
}

/** Apply the daemon settings reconfiguration if selected. */
async function applyDaemonSection(state: SelectiveWizardState): Promise<void> {
  if (!state.sections.includes("daemon")) return;
  console.log("");
  console.log("  Daemon Settings");
  console.log("");
  state.installDaemon = await Confirm.prompt({
    message: "Start on login and run in background?",
    default: true,
  });
}

// ── Section dispatch ──────────────────────────────────────────────────────────

/** Apply all user-selected section reconfigurations sequentially. */
async function applyAllSections(state: SelectiveWizardState): Promise<void> {
  await applyLlmSection(state);
  await applyClassificationModelsSection(state);
  await applyAgentSection(state);
  await applyChannelsSection(state);
  await applyPluginsSection(state);
  await applyGoogleSection(state);
  await applyGitHubSection(state);
  await applySearchSection(state);
  await applyDaemonSection(state);
}

// ── Classification defaults ───────────────────────────────────────────────────

/** Ensure the config has classification defaults set. */
function ensureClassificationDefaults(config: Record<string, unknown>): void {
  if (!config["classification"]) {
    config["classification"] = { mode: "personal", levels: "standard" };
  }
}

// ── Public entry point ────────────────────────────────────────────────────────

/** Build the unchanged-config result when no sections are selected. */
function buildUnchangedResult(configPath: string, spinePath: string): DiveResult {
  console.log("");
  console.log("  No sections selected \u2014 config unchanged.");
  console.log("");
  return { configPath, spinePath, installDaemon: false, channels: [] };
}

/** Enforce that stdin is an interactive terminal. */
function enforceTerminalRequirement(): void {
  if (!Deno.stdin.isTerminal()) {
    log.error("Terminal requirement not met", { operation: "enforceTerminalRequirement", reason: "stdin is not a TTY" });
    console.error("");
    console.error("  Error: the dive wizard requires an interactive terminal.");
    console.error("");
    Deno.exit(1);
  }
}

/** Create the initial wizard state from loaded config and selected sections. */
function createWizardState(options: {
  sections: WizardSection[];
  existingConfig: Record<string, unknown>;
  existingSpine: string;
  spinePath: string;
}): SelectiveWizardState {
  return {
    sections: options.sections,
    config: { ...options.existingConfig },
    existingConfig: options.existingConfig,
    existingSpine: options.existingSpine,
    spinePath: options.spinePath,
    activeChannels: [],
    installDaemon: false,
  };
}

/** Build the final DiveResult from completed wizard state. */
function buildSelectiveResult(
  state: SelectiveWizardState,
  configPath: string,
  spinePath: string,
): DiveResult {
  return {
    configPath,
    spinePath,
    installDaemon: state.installDaemon,
    channels: state.activeChannels,
  };
}

/**
 * Run a selective dive wizard that lets the user choose which sections to
 * reconfigure while preserving the rest of their existing config.
 */
export async function runWizardSelective(baseDir: string): Promise<DiveResult> {
  const configPath = join(baseDir, "triggerfish.yaml");
  const spinePath = join(baseDir, "SPINE.md");
  enforceTerminalRequirement();

  const existingConfig = await loadExistingConfig(configPath);
  if (existingConfig === null) return runWizard(baseDir);

  const existingSpine = await loadExistingSpine(spinePath);
  const sections = await promptSectionSelection();
  if (sections.length === 0) return buildUnchangedResult(configPath, spinePath);

  const state = createWizardState({ sections, existingConfig, existingSpine, spinePath });
  await applyAllSections(state);
  ensureClassificationDefaults(state.config);
  await writeUpdatedConfig(configPath, state.config);

  return buildSelectiveResult(state, configPath, spinePath);
}
